module DataLimitationsHelper
  def accordion_1_title
    'Why are there data gaps?'
  end

  def accordion_2_title
    'Types of data gaps'
  end

  def accordion_3_title
    'Using data'
  end

  def accordion_1_content
    '<p>Collecting marine data is challenging and expensive – understanding the impacts of pressures on both marine species and the people that depend on them requires substantial data, not only on these species but also on biogeochemical and oceanographic processes.</p><p>Ocean-based research is expensive and logistically challenging due to the size and remoteness of the research areas and to the need for advanced technologies and equipment.</p><p>Adequate species identification, either on research vessels or of preserved specimens, is very time intensive.</p><p>Despite an estimated 2.2 million species living in the oceans, it is thought that 91% of these have not yet been described.</p><p>In addition, gaps in specialist skills (e.g. taxonomy, bioinformatics) and/or equipment (e.g. microscopy, digital imagery analysis, genetic analysis) further hamper understanding of marine biodiversity and limit the discovery of new species. This is particularly the case for species that are morphologically similar but genetically distinct, and those groups that have a large number of rare or less common species, such as bacteria.</p><p>Find out more information on data limitations by downloading our companion document (PDF) at <a href="wcmc.io/datalimitations" title="Download the data limitations PDF" target="_blank">wcmc.io/datalimitations.</a></p>'
  end

  def accordion_2_content
    '<p>Accurate and reliable data on the marine environment are frequently scarce, with errors stemming from the low ‘detectability’ of species, species misidentification, and spatial and temporal sampling bias.</p><p>It is estimated that 95% of the ocean remains unexplored, with a strong bias in sampling effort and data availability towards temperate regions in the Northern hemisphere, such as the North Atlantic Ocean.</p><p>In particular, most records for marine species have been obtained from within the exclusive economic zones of Canada, Australia, Alaska, United Kingdom, United States of America, Greenland, Republic of South Africa and Bermuda. Although tropical areas are known to be species rich, data on the species inhabiting them is amongst the poorest. Even within a given animal group, geographic coverage can be heterogeneously distributed.</p><p>In addition to the lack of knowledge about marine species there is also a bias in knowledge and data availability of particular animal groups. For example, nearly half of known marine biodiversity is represented by only three groups (crustaceans, molluscs, and fish), and many of these species are commercially important (Intergovernmental Oceanographic Commission of UNESCO 2014).</p><p>Even charismatic marine groups such as sharks and seahorses lag behind terrestrial groups in the extent of knowledge on their constituent species and the threats they face. Deep sea habitats such as hydrothermal vents and cold seeps are presently under-studied, and so are the plethora of endemic species currently unknown to science that they tend to host.</p><p>Find out more information on data limitations by downloading our companion document (PDF) at <a href="wcmc.io/datalimitations" title="Download the data limitations PDF" target="_blank">wcmc.io/datalimitations.</a></p>'
  end

  def accordion_3_content
    '<p>How data are recorded may influence their reliability and subsequent use (e.g. in models, impacts assessments). For example, caution should be taken when using species spatial distributions that have been estimated using data that were not obtained using comprehensive survey and sampling strategies. In this context, it is imperative to discriminate between ‘no recorded presence’ and ‘identified absence’.</p><p>During a desktop study (e.g. for an environmental impact assessment), failure to find a record a species at a particular location may mean that:</p><ul><li>no sampling has taken place at this location;</li><li>the habitat is not suitable for this species to live, or the habitat is suitable but, due to other factors such as biotic interactions with other species (competition, predation), the species does not generally occupy this habitat;</li><li>the sampling/survey strategy was not adequate (e.g. wrong time of day for species showing diurnal movements; wrong time of year for species showing seasonal migrations; sampling gear unsuited to the target species, patchy spatial distribution missed by the survey path, etc.);</li><li>the species was misidentified as another species;</li><li>the species is rare/elusive, and was therefore not detected, though present; and/or</li><li>observed data were not shared (e.g. with online databases) or published (in the grey or peer-reviewed literature).</li></ul><p>Obtaining valid ‘absence data’ in the marine environment, where detection probabilities are generally low, remains difficult and rare. Species absence records are usually only available at a limited number of sites as the absence of a species is only ascertained when a given site has been exhaustively explored.</p><p>Find out more information on data limitations by downloading our companion document (PDF) at <a href="wcmc.io/datalimitations" title="Download the data limitations PDF" target="_blank">wcmc.io/datalimitations.</a></p>'
  end
end